### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by TieSKey** [christian-roggia/vndb#1]
I had to change the dockerfile this way

```
RUN apt-get install -y --force-yes --no-install-recommends \
        libssl-dev=$OPENSSL_VERSION \
.....
```

I'm not used to docker but I think the libssl of the base image has a greater version or something.

**Comment by christian-roggia** [comment]
Fixed in f3d031d66dc412a96aedce21d6c8ac4c4c7f185e.
